notifications:
  email: false

language: node_js
sudo: false
node_js: stable

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: update
